### ISSUE TITLE
When mounting how would I extract ExtData

### ISSUE THREAD

**Issue by Cracko298** [J-D-K/FsLib#1]
I've been trying conventional means, can't seem to open it in any other way, besides FsLib.
Which doesn't have a built in extract/copy function.

How exactly would I go about extract said ExtData?

**Comment by J-D-K** [comment]
What game or archive ID are you trying to open? I'll show ya how it's supposed to work. It's not finished yet, but it can get the job done if that's all you're after.

Imagine trying to do this eight years ago with next to no documentation cause that's what I had to do.

**Comment by Cracko298** [comment]
Yeah, the FSUSER docs are really screwed up.
The extdata ID is: 00001b87.
I am able to open it, but I am unable to access it with the rest of the Libctru docs.

I'm realitively new to 3ds hb development so yeah.

**Comment by J-D-K** [comment]
OK. Thank you. Let me go **_buy_** that and I'll have something in a little while so you at least have a rough idea of what you should do. I might need to do some testing writing to it first because writing to ExtData was kind of odd if I remember right.

**Comment by Cracko298** [comment]
Lol, and thank you, man. I appreciate you helping me out!

**Comment by J-D-K** [comment]
Hit an interesting snag. It's mostly working, but all of the saves are inside a folder named Minecraft Worlds, and I'm having issues with it listing what's in it. Taking a quick break. 

It's always Minecraft that's the most fun to deal with. 3DS and Switch.

**Comment by Cracko298** [comment]
> Hit an interesting snag. It's mostly working, but all of the saves are inside a folder named Minecraft Worlds, and I'm having issues with it listing what's in it. Taking a quick break. 
> 
> It's always Minecraft that's the most fun to deal with. 3DS and Switch. 

Yes that's exactly where my implementation went south.
The base64 hashes i got stuck on, I thought they where null bytes at first but I couldn't return the hex char list of string.

I do remember hearing Minecraft was a pain a few times when dealing with saves on Sony and Nintendo consoles.

**Comment by J-D-K** [comment]
In this case it’s because my Path class is allocated on the stack and uses UTF-16 paths. The ExtData has so many subdirectories and files that it’s running out of stack memory. Still deciding how to tackle it. Heap allocated arrays, just using underlying u16strings, or vectors. I kept it on the stack to make it simpler but I guess that isn’t possible.

**Comment by Cracko298** [comment]
Would it be viable to instead of reading one or two directories, and reclusively copy them to the sdmc? Instead of reading everything all at once, or is that not the problem, and instead, the path limit is being reached because of how many files/folders are in said ExtData?

Each world has a random hash, so it'd be near impossible to have a predefined path before attempting to read it all. So that wouldn't work, I know Checkpoint does something weird with ExtData like that, but it's extremely primitive and slow for only a few mb of data for the game itself.

Wonder how we'd be able to bypass said restriction (maybe a bigger buffer). Idk I'm just throwing stuff out there and hoping something sticks.

**Comment by J-D-K** [comment]
https://github.com/J-D-K/fslib/blob/main/3DS/Examples/ExtData/source/Main.cpp

If you need help understanding anything better let me know. You can also catch me on Discord or GBATemp instead of git issues. I don't check my email too often. Clone the repo, type `make 3ds`, and it will build everything for you. That's the basic 1:1 in and out way, but if the worlds get too big for the 3DS to buffer like that, you're going to need to read it in chunks. I commented the hell out of it, but compared to the underlying stuff I'm taking care of, that's next to nothing.

I'll keep an eye out. Sorry it took a while. I'm not feeling too good today.

**Comment by Cracko298** [comment]
Absolutely ill take a look and impliment it into something in working on atm.
Will I need to update FsLib or should it work reguardless nomatter version/release?

Just asking, and yup you got it. I just used the makefile in the 3ds directory original to build the og testapp.

**Comment by Cracko298** [comment]
Thanks again man, I appreciate you helping me out as well!!!!

**Comment by J-D-K** [comment]
It's a good idea to update it. I wouldn't reverse the backup process though. As in, please don't try SD -> ExtData yet. There's something off about how ExtData works and I'm trying to pin down how to handle with FsLib. JKSM working slightly differently, so it wasn't an issue there.

**Comment by Cracko298** [comment]
Yeah, right now I was focusing on getting the backup portion done rather than importing atm.

Anyway, this is what I was attempting to create: https://github.com/Cracko298/MC3DS-WorldManager

I'll keep you updated if I have anymore issues, I appreciate you taking your time to help a novice lol.

**Comment by J-D-K** [comment]
No problem at all. I hate people like that. The ones that act holier than thou and like you're not worth their time.

**Comment by J-D-K** [comment]
Just some issues that I've noticed today:

1. Minecraft does this annoying thing where it calls CreateFile with a starting size, probably because it saves everything to ExtData, but doesn't actually write data to certain parts of the file. It's not the only game that does this.
2. I used to correct for this in JKSM, which is where Checkpoint got its fix from. I used to write the error code over the sections I can't read but:
3. I'm not sure if that will corrupt the save or not. I need to check. The 3DS has some odd stuff you need to deal with.

I'm still deciding how to handle it, because I wanted FsLib to work like a cross between C stdio and C++ fstream. The Read and Write functions return how much was read or written. Returning 0 is how I indicate failure, but filling the buffer with blank 0s and returning size anyway would defeat the purpose of that. 3DS can be a major headache. Hope I didn't cause any problems. I'm aware of it. If you build the latest version of the example, you'll see what I'm talking about.

**Comment by J-D-K** [comment]
Oh, and if you do build the example, don't try importing from SD yet. I can implement my old fix, but yeah, as it is, it will have some issues.

**Comment by Cracko298** [comment]
> Just some issues that I've noticed today:
> 
> 1. Minecraft does this annoying thing where it calls CreateFile with a starting size, probably because it saves everything to ExtData, but doesn't actually write data to certain parts of the file. It's not the only game that does this.
> 2. I used to correct for this in JKSM, which is where Checkpoint got its fix from. I used to write the error code over the sections I can't read but:
> 3. I'm not sure if that will corrupt the save or not. I need to check. The 3DS has some odd stuff you need to deal with.
> 
> I'm still deciding how to handle it, because I wanted FsLib to work like a cross between C stdio and C++ fstream. The Read and Write functions return how much was read or written. Returning 0 is how I indicate failure, but filling the buffer with blank 0s and returning size anyway would defeat the purpose of that. 3DS can be a major headache. Hope I didn't cause any problems. I'm aware of it. If you build the latest version of the example, you'll see what I'm talking about. 

Ah, yes, several files are called i saw. It also creates temporary files with either 0 bytes of data, or a set ammount but then doesn't actually save them instead uses them as a reference point to eventually save the game whenever that is.

It's something weird with the game, in which it's autosaving is probably what is causing the issue. I compiled it and see what you meant. I'm also working on something that uses fslib but will handle these use cases as well for mc3ds I have a few things done specifically with these either unusable or temporary files the game creates and deletes apon system restart, idk how it does that.

I remember when I attempted to make my first 3ds homebrew app/tool that converted attribute files too json and back and that was a pain in forgot how I fixed it. But yea, the 3ds from the little exp I've had is a huge pain to code with. I'm amazed on how you, yellows8, mechanicaldragon, etc all made awesome apps when I can barely get hello world printed 9 times out of 10.

**Comment by Cracko298** [comment]
> Oh, and if you do build the example, don't try importing from SD yet. I can implement my old fix, but yeah, as it is, it will have some issues. 

Noted, thanks for the heads up!

**Comment by J-D-K** [comment]
Small update. I implemented my old fix and this is what I got after restoring:
![2024-11-09_11-58-06 978_top](https://github.com/user-attachments/assets/7f1717b4-262f-483d-8c55-6136e50af523)
I'm pretty sure Minecraft has colors besides gray. I'm guessing the only safe way to pull this off might be reading the files byte by byte into a buffer or vector and then writing the buffer after a certain amount is read.

This error is a really hard one to fix and preserve everything while still being fast enough that people don't complain.

**Comment by Cracko298** [comment]
It just looks like the level.dat might be off somewhat.
Y seems to be greater than 128, possibly 129, 130, or 131.

The file sizes are always a certain amount depending on said file so would that be a possible fix.

Maybe we have a file that's 0x2000 bytes always, could we divide that into multiple chunks say 16 bytes each chunk which is manageable to some degree, could we then reconstruct said file onto the sdmc?

**Comment by J-D-K** [comment]
Give me some time. I’ll show you what I mean. It will work 100% and get everything it possibly can from the files. Speed shouldn’t be too much of an issue since it’s going to be read byte by byte, not written byte by byte.

**Comment by Cracko298** [comment]
> Give me some time. I’ll show you what I mean. It will work 100% and get everything it possibly can from the files. Speed shouldn’t be too much of an issue since it’s going to be read byte by byte, not written byte by byte.

I keep forgetting that write speeds are terrible on 3ds. Again, thanks, man! This library you've made and you have been a huge help!

**Comment by J-D-K** [comment]
Hey. Just so ya know, I'm not ignoring ya. I'm working on the Switch version of JKSV and a lot of the stuff I'm going to be doing to FsLib is Switch only for the next few days. I wouldn't build and try to use the 3DS ExtData example right now. I need to change the return value of something before it'll work correctly. I'm kind of spread thin as it is, but I needed to fix something for Switch really bad so I could continue. I'll reply once I get some stuff sorted.

Thanks for being patient dude. I run a mostly one man show.

**Comment by Cracko298** [comment]
> Hey. Just so ya know, I'm not ignoring ya. I'm working on the Switch version of JKSV and a lot of the stuff I'm going to be doing to FsLib is Switch only for the next few days. I wouldn't build and try to use the 3DS ExtData example right now. I need to change the return value of something before it'll work correctly. I'm kind of spread thin as it is, but I needed to fix something for Switch really bad so I could continue. I'll reply once I get some stuff sorted.
> 
> Thanks for being patient dude. I run a mostly one man show.

There is no need to apologize. You run litterally the best save managers for both systems. I'm trying my own experimental stuff using fslib, and I have some success.
Other apps take teams and tons of people to develop them. Having multiple projects keeps you from being burned out.

I'd be alot better at C and C++ outside of libctru, it just makes it difficult to understand anything. Your lib is basically the best library/wrapper I've used that's compatible with libctru and makes it much easier to manage and understand what's going on.

Take your time, I'll check in periodically for any updates via the repo commits. In between those ill try to find my own screwy solutions for it lol.

Appreciate your time and patience with me as well.

**Comment by J-D-K** [comment]
Hey. I'm going to port the path changes over to 3DS soon and I'll get back to ya. Unfortunately JKSV's Google Drive and WebDav code needs some work and that's a major pain in the ass. I have a million security alerts in my inbox just from debugging the login code.

**Comment by Cracko298** [comment]
Google Drive's API sucks (really bad).
I've dealt with it before, so does the YouTube and Translate API.

**Comment by J-D-K** [comment]
I'm getting somewhere. Does Checkpoint _actually_ work with Minecraft? I just checked its code and it, unsurprisingly, still has my workaround in place. FsLib's is actually more accurate than that one, but I'm still having issues with restoring causing a gray, empty looking map. I'm considering trying to implement an AccurateRead function with the warning it's really slow cause I don't see any other way to get around this.

**Comment by Cracko298** [comment]
Yes, Checkpoint Backups and Restore points work flawlessly, just really really slow. And anything is better than working directly with the FileSystem that libctru provides, I wasn't able to get anywhere at all.

**Comment by J-D-K** [comment]
That makes me suspect it's a buffer size difference. There are differences, but Checkpoint's FS code is **extremely** similar to JKSM's.  I'll see what size he uses cause I know I went as large as possible without choking the 3DS.

**Comment by J-D-K** [comment]
Nevermind it's not the buffer size. Checkpoint has a 1:1 copy of what original JKSM had: I used to correct for the error, but not write anything to the buffer. What I did with FsLib was memset the buffer to blank it on an error. I removed that and the files are identical. FsLib is still more accurate when correcting for file and buffer size on an error though. I'll see if threaded read and write makes a difference for speed and push the finished example for you. It's working. I just had to listen to my old self and improve it in some areas. It won't be long now.

**Comment by Cracko298** [comment]
I appreciate it man! Will the example provide a basic rendition of these changes per chance?

Thanks a bunch, you're one of very few that are willing to help people who don't know what they're doing (like me), in the scene.
Thank you man!

**Comment by J-D-K** [comment]
When I was a teenager PSP hacking and homebrew was all the rage. I don't use the same username anymore, but I've had encounters with some pretty well known people from back then and PS3, and a lot of them were egotistical assholes. I make it a point to not be like them. If you're another well known dev talking shit, then the gloves come off. Someone who needs to tell me something or wants some help? I'll do whatever I can as long as I have the time.

**Comment by J-D-K** [comment]
I've updated the example. The biggest difference is that I've made the paths work a bit different. They no longer use trailing slashes and they now have an operator that can actually construct them like this:
```cpp
FsLib::Path TestPath = u"sdmc:/MinecraftSaves";
FsLib::Path SubTestPath = TestPath / u"SaveFolderHere" / u"minecraftWorlds" / ImaginaryDirectory.GetEntryAt(i);
```
The + and += operators are still there, but the / and /= are kind of like training wheels, I guess? I just find think it's cool you can do that in C++...

The copying is threaded. Let me know if it's fast enough. It should whip JKSM and Checkpoint's asses... unless I get a chance to use it myself.

**Comment by J-D-K** [comment]
Just caught one final thing that prevented importing correctly. It works 100% both ways now for sure. Latest commit is what you're going to need.

**Comment by Cracko298** [comment]
Thank you man! Just got off from my Job.
I'll take a look tomorrow and do some implementing then, again thanks so much for your help!

**Comment by J-D-K** [comment]
No problem dude. If you need any help, just ask wherever works for ya. I found a half finished JKSM rewrite on a hard drive. Getting it integrated into that outta help fish out any bugs I haven't noticed.

**Comment by J-D-K** [comment]
Just curious dude. You have any idea what's in this and if it's important? I don't have it ready to dump anything yet, so I can't check myself. I didn't even know Minecraft had BOSS... Just asking in case you need it.
![Minecraft Boss](https://github.com/user-attachments/assets/f1c90c8c-8951-4ded-830a-3fd6e9e46365)

**Comment by Cracko298** [comment]
Minecraft creates a BOSS folder but never uses it and wipes save data if it's removed.

I haven't done anything with using it FsLib yet (BOSS data)

**Comment by J-D-K** [comment]
OK, so I forked MC3DS-WorldManager and it seems to me you're much more familiar with C than C++, correct? I don't think C has a lot, if any, standard functions for dealing with UTF-16 formatted strings. If you think it would be easier for ya, I can show you how to accomplish the same thing with ctrulib. The only problem is it comes with quite a bit more overhead than what FsLib does. I'm not sure how much of it is noticeable in the end, but it definitely does. I'll let it up to you. 

Edit: Going the ctrulib route will also allow you to use C stdio functions, while FsLib kinda does its own thing in comparison.

**Comment by Cracko298** [comment]
Yes, i am more familiar with C rather than C++. Even though they're somewhat the same, I just prefer C because it's somewhat simpler in a way.

**Comment by J-D-K** [comment]
I made a pull request that should get you going in the right direction. I really _do_ mean what I said in the notes at the end. I'm not being a jerk: I'm just being honest about what I think about ctrulib's archive_dev.c file.

**Comment by Cracko298** [comment]
I just merged it, it looks all good.
Will be compiling asap, I'm not home rn lol so I can't do it atm.

Thank you for the suggestions and I will be adding some of them in, again thx man!!!
